/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jniplay_JavaApp */

#ifndef _Included_jniplay_JavaApp
#define _Included_jniplay_JavaApp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jniplay_JavaApp
 * Method:    nativeAdd
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_jniplay_JavaApp_nativeAdd
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
